services:

  postgres:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:java -version
      - POSTGRES_DB=db
      - POSTGRES_USER=login
      - POSTGRES_PASSWORD=example

  adminer:
    image: adminer
    restart: always
    ports:
      - 9999:9999